// SPDX-License-Identifier: MIT OR Apache-2.0
//! `build.rs` codegen for [grpcuds](https://crates.io/crates/grpcuds)
//! servers and clients: a server trait + a typed client stub, generated
//! from your `.proto`.
//!
//! Messages are generated by [prost-build]; this crate plugs a
//! [`ServiceGenerator`](prost_build::ServiceGenerator) into it that emits,
//! per `service`:
//!
//! - a **server trait** with one method per RPC — unary methods are
//!   `fn m(&self, req) -> Result<Resp, grpcuds::Status>`, server-streaming
//!   methods are `fn m(&self, req, writer: grpcuds::MessageWriter<Resp>) ->
//!   grpcuds::Status`;
//! - an **`add_*_service` function** that registers every method of an
//!   `Arc<impl Trait>` on a `grpcuds::ServerBuilder`;
//! - a **`*Client` struct** wrapping [`grpcuds::Client`] with one typed
//!   method per RPC (the method paths are baked in) — unary methods return
//!   `Result<Resp, grpcuds::Status>`, server-streaming ones return a typed
//!   stream to iterate with `.message()?`.
//!
//! Either half can be switched off with [`Builder::build_server`] /
//! [`Builder::build_client`].
//!
//! ```toml
//! # Cargo.toml — the generated message types derive `::prost::Message`,
//! # so the consuming crate depends on `prost` DIRECTLY.
//! [dependencies]
//! grpcuds = { version = "*", features = ["server", "client", "prost"] }
//! prost = "0.13"
//!
//! [build-dependencies]
//! grpcuds-build = "*"
//! ```
//!
//! ```no_run
//! // build.rs
//! grpcuds_build::compile_protos("proto/echo.proto").unwrap();
//! ```
//!
//! ```ignore
//! // main.rs  (generated code lives in OUT_DIR, so this doc block is
//! //  `ignore`; the same shape is compiled AND run end-to-end by the
//! //  `tests/rust` cells — e.g. `domains/ble-domain` + `cells/ble-gg`)
//! mod pb { grpcuds::include_proto!("echo"); }
//!
//! // Server side: implement the trait, register it.
//! struct MyEcho;
//! impl pb::Echo for MyEcho {
//!     fn unary(&self, req: pb::HiRequest) -> Result<pb::HiReply, grpcuds::Status> { todo!() }
//! }
//! let b = pb::add_echo_service(grpcuds::Server::builder().bind(sock), MyEcho.into());
//! let running = b.build()?.run()?;
//!
//! // Client side: the generated stub.
//! let mut client = pb::EchoClient::connect(sock)?;
//! let reply = client.unary(pb::HiRequest { text: "hi".into() })?;
//! ```
//!
//! The consuming crate needs three things:
//!
//! - **`grpcuds` features**: `prost` (the generated code calls its typed
//!   APIs), plus `server` for the trait + registration half and/or `client`
//!   for the stub half — enable only the half you use.
//! - **a direct `prost` dependency**: the generated messages derive
//!   `::prost::Message`.
//! - **`protoc` on `PATH`** (or the `PROTOC` env var) — prost-build runs it.
//!
//! Client-streaming and bidirectional RPCs are **rejected at build time**
//! (like the C++ plugin): the runtime is unary + server-streaming.
//!
//! [prost-build]: https://docs.rs/prost-build
//! [`grpcuds::Client`]: https://docs.rs/grpcuds

use std::fmt::Write as _;
use std::io;
use std::path::Path;

/// Compile one `.proto` (include path = its parent directory) with grpcuds
/// service generation — the common one-call entry point.
pub fn compile_protos(proto: impl AsRef<Path>) -> io::Result<()> {
    let proto = proto.as_ref();
    let include = proto.parent().unwrap_or_else(|| Path::new("."));
    configure().compile_protos(&[proto], &[include])
}

/// A configured codegen run. Wraps [`prost_build::Config`]; use
/// [`config`](Builder::config) for prost options (type attributes, …).
pub fn configure() -> Builder {
    Builder {
        config: prost_build::Config::new(),
        server: true,
        client: true,
    }
}

/// Builder returned by [`configure`].
pub struct Builder {
    config: prost_build::Config,
    server: bool,
    client: bool,
}

impl Builder {
    /// Mutable access to the underlying prost-build configuration
    /// (`btree_map`, `type_attribute`, `out_dir`, …).
    pub fn config(&mut self) -> &mut prost_build::Config {
        &mut self.config
    }

    /// Generate the server trait + `add_*_service` registration (default
    /// `true`). The generated code needs `grpcuds`'s `server` + `prost`
    /// features.
    pub fn build_server(mut self, enabled: bool) -> Self {
        self.server = enabled;
        self
    }

    /// Generate the typed `*Client` stub (default `true`). The generated
    /// code needs `grpcuds`'s `client` + `prost` features.
    pub fn build_client(mut self, enabled: bool) -> Self {
        self.client = enabled;
        self
    }

    /// Run protoc + prost + the grpcuds service generator over `protos`.
    pub fn compile_protos(
        mut self,
        protos: &[impl AsRef<Path>],
        includes: &[impl AsRef<Path>],
    ) -> io::Result<()> {
        self.config.service_generator(Box::new(GrpcUdsGenerator {
            server: self.server,
            client: self.client,
        }));
        self.config.compile_protos(protos, includes)
    }
}

struct GrpcUdsGenerator {
    server: bool,
    client: bool,
}

impl prost_build::ServiceGenerator for GrpcUdsGenerator {
    fn generate(&mut self, service: prost_build::Service, buf: &mut String) {
        for m in &service.methods {
            if m.client_streaming {
                panic!(
                    "grpcuds supports unary and server-streaming RPCs only; \
                     {}.{}/{} is client-streaming or bidirectional",
                    service.package, service.proto_name, m.proto_name
                );
            }
        }

        let trait_name = &service.name; // CamelCase service name
        let snake = to_snake(&service.name);
        let add_fn = if snake.ends_with("_service") {
            format!("add_{snake}")
        } else {
            format!("add_{snake}_service")
        };

        if self.client {
            self.generate_client(&service, buf);
        }
        if !self.server {
            return;
        }

        // ---- server trait -------------------------------------------------
        let _ = writeln!(
            buf,
            "/// Generated grpcuds server trait for `{}.{}`.",
            service.package, service.proto_name
        );
        for line in service.comments.leading.iter() {
            let _ = writeln!(buf, "///{}", line);
        }
        let _ = writeln!(buf, "pub trait {trait_name}: Send + Sync + 'static {{");
        for m in &service.methods {
            for line in m.comments.leading.iter() {
                let _ = writeln!(buf, "    ///{}", line);
            }
            if m.server_streaming {
                let _ = writeln!(
                    buf,
                    "    fn {}(&self, request: {}, writer: ::grpcuds::MessageWriter<{}>) -> ::grpcuds::Status;",
                    m.name, m.input_type, m.output_type
                );
            } else {
                let _ = writeln!(
                    buf,
                    "    fn {}(&self, request: {}) -> ::core::result::Result<{}, ::grpcuds::Status>;",
                    m.name, m.input_type, m.output_type
                );
            }
        }
        let _ = writeln!(buf, "}}");

        // ---- registration -------------------------------------------------
        let _ = writeln!(
            buf,
            "/// Register every `{}.{}` method of `svc` on `builder`.",
            service.package, service.proto_name
        );
        let _ = writeln!(
            buf,
            "pub fn {add_fn}<T: {trait_name}>(\n    builder: ::grpcuds::ServerBuilder,\n    svc: ::std::sync::Arc<T>,\n) -> ::grpcuds::ServerBuilder {{"
        );
        let _ = writeln!(buf, "    let mut b = builder;");
        for m in &service.methods {
            let path = format!(
                "/{}.{}/{}",
                service.package, service.proto_name, m.proto_name
            );
            if m.server_streaming {
                let _ = writeln!(
                    buf,
                    "    let s = svc.clone();\n    b = b.add_server_streaming_msg(\"{path}\", move |req, w: &::grpcuds::MessageWriter<_>| s.{}(req, w.clone()));",
                    m.name
                );
            } else {
                let _ = writeln!(
                    buf,
                    "    let s = svc.clone();\n    b = b.add_unary_msg(\"{path}\", move |req| s.{}(req));",
                    m.name
                );
            }
        }
        let _ = writeln!(buf, "    b\n}}");
    }
}

impl GrpcUdsGenerator {
    fn generate_client(&self, service: &prost_build::Service, buf: &mut String) {
        let client_name = format!("{}Client", service.name);
        let _ = writeln!(
            buf,
            "/// Generated grpcuds client for `{}.{}` (needs the `client` + `prost` features of `grpcuds`).",
            service.package, service.proto_name
        );
        for line in service.comments.leading.iter() {
            let _ = writeln!(buf, "///{}", line);
        }
        let _ = writeln!(buf, "pub struct {client_name} {{");
        let _ = writeln!(buf, "    inner: ::grpcuds::Client,");
        let _ = writeln!(buf, "}}");
        let _ = writeln!(buf, "impl {client_name} {{");
        let _ = writeln!(
            buf,
            "    /// Connect to a grpcuds (or any gRPC-over-UDS) server at `path`.\n    \
             pub fn connect(path: impl ::core::convert::AsRef<::std::path::Path>) -> ::core::result::Result<Self, ::grpcuds::Error> {{\n        \
             ::core::result::Result::Ok(Self {{ inner: ::grpcuds::Client::connect(path)? }})\n    }}"
        );
        let _ = writeln!(
            buf,
            "    /// Wrap an already-connected [`::grpcuds::Client`].\n    \
             pub fn from_client(inner: ::grpcuds::Client) -> Self {{\n        Self {{ inner }}\n    }}"
        );
        let _ = writeln!(
            buf,
            "    /// The underlying untyped client (e.g. for raw byte calls).\n    \
             pub fn into_inner(self) -> ::grpcuds::Client {{\n        self.inner\n    }}"
        );
        let _ = writeln!(
            buf,
            "    /// Per-call timeout passthrough — see [`::grpcuds::Client::set_timeout`].\n    \
             pub fn set_timeout(&mut self, timeout: ::core::option::Option<::std::time::Duration>) {{\n        \
             self.inner.set_timeout(timeout)\n    }}"
        );
        for m in &service.methods {
            let path = format!(
                "/{}.{}/{}",
                service.package, service.proto_name, m.proto_name
            );
            for line in m.comments.leading.iter() {
                let _ = writeln!(buf, "    ///{}", line);
            }
            if m.server_streaming {
                let _ = writeln!(
                    buf,
                    "    pub fn {}(&mut self, request: {}) -> ::core::result::Result<::grpcuds::TypedStreaming<'_, {}>, ::grpcuds::Status> {{\n        \
                     self.inner.server_streaming_msg(\"{path}\", &request)\n    }}",
                    m.name, m.input_type, m.output_type
                );
            } else {
                let _ = writeln!(
                    buf,
                    "    pub fn {}(&mut self, request: {}) -> ::core::result::Result<{}, ::grpcuds::Status> {{\n        \
                     self.inner.unary_msg(\"{path}\", &request)\n    }}",
                    m.name, m.input_type, m.output_type
                );
            }
        }
        let _ = writeln!(buf, "}}");
    }
}

/// CamelCase → snake_case for the `add_*_service` function name.
fn to_snake(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 4);
    for (i, c) in s.chars().enumerate() {
        if c.is_ascii_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
        } else {
            out.push(c);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use prost_build::ServiceGenerator as _;

    fn gen_with(tag: &str, proto: &str, tweak: impl FnOnce(Builder) -> Builder) -> String {
        // Drive prost-build end to end in a temp dir so Service metadata is
        // exactly what real builds see. Unique dir per test (they run in
        // parallel threads of one process).
        let dir =
            std::env::temp_dir().join(format!("grpcuds-build-test-{}-{tag}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let proto_path = dir.join("t.proto");
        std::fs::write(&proto_path, proto).unwrap();
        let out = dir.join("out");
        std::fs::create_dir_all(&out).unwrap();
        let mut b = tweak(configure());
        b.config().out_dir(&out);
        b.compile_protos(&[&proto_path], &[&dir]).unwrap();
        std::fs::read_to_string(out.join("echo.rs")).unwrap()
    }

    fn gen_for(tag: &str, proto: &str) -> String {
        gen_with(tag, proto, |b| b)
    }

    const PROTO: &str = r#"
syntax = "proto3";
package echo;
message HiRequest { string text = 1; }
message HiReply { string text = 1; }
message Tick { uint32 n = 1; }
service Echo {
  rpc Hi(HiRequest) returns (HiReply);
  rpc Watch(HiRequest) returns (stream Tick);
}
"#;

    #[test]
    fn generates_trait_and_registration() {
        // prost-build reformats the output (prettyplease), so compare on a
        // whitespace-normalized view.
        let raw = gen_for("trait", PROTO);
        let code = raw.split_whitespace().collect::<Vec<_>>().join(" ");
        for needle in [
            "pub trait Echo: Send + Sync + 'static {",
            "fn hi( &self, request: HiRequest, ) -> ::core::result::Result<HiReply, ::grpcuds::Status>;",
            "fn watch( &self, request: HiRequest, writer: ::grpcuds::MessageWriter<Tick>, ) -> ::grpcuds::Status;",
            "pub fn add_echo_service<T: Echo>(",
            "b = b.add_unary_msg(\"/echo.Echo/Hi\", move |req| s.hi(req))",
            "add_server_streaming_msg( \"/echo.Echo/Watch\",",
        ] {
            assert!(code.contains(needle), "missing {needle:?} in:\n{raw}");
        }
    }

    #[test]
    fn generates_client_stub() {
        let raw = gen_for("client", PROTO);
        let code = raw.split_whitespace().collect::<Vec<_>>().join(" ");
        for needle in [
            "pub struct EchoClient {",
            "inner: ::grpcuds::Client,",
            "pub fn connect( path: impl ::core::convert::AsRef<::std::path::Path>,",
            "pub fn from_client(inner: ::grpcuds::Client) -> Self {",
            "pub fn into_inner(self) -> ::grpcuds::Client {",
            "pub fn set_timeout( &mut self, timeout: ::core::option::Option<::std::time::Duration>, ) {",
            "pub fn hi( &mut self, request: HiRequest, ) -> ::core::result::Result<HiReply, ::grpcuds::Status> {",
            "self.inner.unary_msg(\"/echo.Echo/Hi\", &request)",
            "pub fn watch( &mut self, request: HiRequest, ) -> ::core::result::Result<::grpcuds::TypedStreaming<'_, Tick>, ::grpcuds::Status> {",
            "self.inner.server_streaming_msg(\"/echo.Echo/Watch\", &request)",
        ] {
            assert!(code.contains(needle), "missing {needle:?} in:\n{raw}");
        }
    }

    #[test]
    fn build_client_false_omits_stub() {
        let raw = gen_with("no-client", PROTO, |b| b.build_client(false));
        assert!(!raw.contains("EchoClient"), "stub leaked into:\n{raw}");
        assert!(raw.contains("pub trait Echo"), "trait missing in:\n{raw}");
    }

    #[test]
    fn build_server_false_omits_trait() {
        let raw = gen_with("no-server", PROTO, |b| b.build_server(false));
        assert!(!raw.contains("pub trait Echo"), "trait leaked into:\n{raw}");
        assert!(
            !raw.contains("add_echo_service"),
            "registration leaked into:\n{raw}"
        );
        assert!(
            raw.contains("pub struct EchoClient"),
            "stub missing in:\n{raw}"
        );
    }

    #[test]
    #[should_panic(expected = "client-streaming or bidirectional")]
    fn rejects_client_streaming() {
        let mut g = GrpcUdsGenerator {
            server: true,
            client: true,
        };
        let svc = prost_build::Service {
            name: "Bad".into(),
            proto_name: "Bad".into(),
            package: "p".into(),
            comments: Default::default(),
            methods: vec![prost_build::Method {
                name: "up".into(),
                proto_name: "Up".into(),
                comments: Default::default(),
                input_type: "X".into(),
                output_type: "Y".into(),
                input_proto_type: ".p.X".into(),
                output_proto_type: ".p.Y".into(),
                options: Default::default(),
                client_streaming: true,
                server_streaming: false,
            }],
            options: Default::default(),
        };
        let mut buf = String::new();
        g.generate(svc, &mut buf);
    }
}
